version: "3.8"

services:
  db:
    image: library/postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    build: .
    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    restart: "on-failure"

volumes:
  postgres_data:
  static_volume:

