# Generated by Django 3.1.7 on 2021-03-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_create_manufacturer_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default=None, max_length=150)),
                ('manufacturer',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.manufacturer')
                 ),
            ],
        ),
    ]
